# The below is the copyright notice of original file:
# Copyright (c) 2021 anatawa12 and other contributors
# This file is part of fixRTM, released under GNU LGPL v3 with few exceptions
# See LICENSE at https://github.com/fixrtm/fixRTM for more details

name: Feature Request [EN]
description: Create a request to add some feature
labels: [enhancement]
assignees:
  - Kai-Z-JP
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature.

        If you're using machine translation,
        please write in both your native language and English machine translated
        to avoid misreading and un-understandable English due to mistake of machine translator.

  - type: checkboxes
    id: terms
    attributes:
      label: Feature report check list
      options:
        - label: What you want is not included in the latest (including prerelease) version of KaizPatchX.
          required: true
        - label: You couldn't find same request in the issues.
          required: true

  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you want.
    validations:
      required: true
